package TaskManager.shared.DAOs;

import TaskManager.shared.exceptions.AlreadyExistsException;
import TaskManager.shared.models.Collaborator;
import models.*;
import exceptions.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.NoSuchElementException;
import java.util.HashSet;
import java.util.Set;

public class DAOCollaborator extends DAO<Collaborator> {

    protected final static String TABLE = "Collaborator";
    protected final static String FIELD_ID = "id";
    protected final static String FIELD_FIRSTNAME = "firstName";
    protected final static String FIELD_LASTNAME = "lastName";

    @Override
    public Collaborator find(int id) throws SQLException {
        Connection connection = Database.getConnection();
        String query = "SELECT * FROM " + TABLE + " WHERE " + FIELD_ID + " = ?";
        PreparedStatement stmt = null;
        ResultSet rs = null;
        Collaborator collabo = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setInt(1, id);

            rs = stmt.executeQuery();
            if (rs.next())
                collabo = getResult(rs);
        } finally {
            closeStatementAndResulSet(stmt, rs);
        }
        return collabo;
    }

    @Override
    public void create(Collaborator objectToCreate) throws AlreadyExistsException, SQLException {
        if (checkAlreadyExists(objectToCreate) >= 0)
            throw new AlreadyExistsException("This collaborator already exists in database.");

        Connection connection = Database.getConnection();
        String query = "INSERT INTO " + TABLE + " (" + FIELD_FIRSTNAME + ", " + FIELD_LASTNAME + ") VALUES (?, ?)";
        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setString(1, objectToCreate.getFirstName());
            stmt.setString(2, objectToCreate.getLastName());

            stmt.executeUpdate();
            getNewId(objectToCreate);
        } finally {
            closeStatementAndResulSet(stmt, null);
        }
    }

    /**
     * Retrieve the id generated by the database after an INSERT and set it on the object
     * @param newObject the object just inserted in the database
     * @throws SQLException if the database could not be reached
     */
    private void getNewId(Collaborator newObject) throws SQLException {
        Connection connection = Database.getConnection();
        String query = "SELECT " + FIELD_ID + " FROM " + TABLE +
                " WHERE " + FIELD_FIRSTNAME + " = ? AND " + FIELD_LASTNAME + " = ?";
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setString(1, newObject.getFirstName());
            stmt.setString(2, newObject.getLastName());

            rs = stmt.executeQuery();
            if (rs.next())
                newObject.setId(rs.getInt(FIELD_ID));
        } finally {
            closeStatementAndResulSet(stmt, rs);
        }
    }

    @Override
    public void update(Collaborator objectToUpdate) throws SQLException, NoSuchElementException {
        if (find(objectToUpdate.getId()) == null)
            throw new NoSuchElementException("[ERROR] There is no Collaborator with the id " + objectToUpdate.getId());

        Connection connection = Database.getConnection();
        String query = "UPDATE " + TABLE + " SET " + FIELD_FIRSTNAME + " = ?, " + FIELD_LASTNAME + " = ? WHERE " + FIELD_ID + " = ?";
        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setString(1, objectToUpdate.getFirstName());
            stmt.setString(2, objectToUpdate.getLastName());
            stmt.setInt(3, objectToUpdate.getId());

            stmt.executeUpdate();
        } finally {
            closeStatementAndResulSet(stmt, null);
        }
    }

    @Override
    public void delete(Collaborator objectToDelete) throws SQLException, NoSuchElementException {
        Connection connection = Database.getConnection();
        String query = "DELETE FROM " + TABLE + " WHERE " + FIELD_ID + " = ?";
        PreparedStatement stmt = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setInt(1, objectToDelete.getId());

            if (stmt.executeUpdate() == 0)
                throw new NoSuchElementException("[ERROR] There is no Collaborator with the id " + objectToDelete.getId());
        } finally {
            closeStatementAndResulSet(stmt, null);
        }
    }

    @Override
    public Set<Collaborator> findAll() throws SQLException {
        Connection connection = Database.getConnection();
        String query = "SELECT * FROM " + TABLE;
        Set<Collaborator> collaborators = new HashSet<>();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            stmt = connection.prepareStatement(query);
            rs = stmt.executeQuery();

            while (rs.next())
                collaborators.add(getResult(rs));
        } finally {
            closeStatementAndResulSet(stmt, rs);
        }
        return collaborators;
    }

    /**
     * Check if a Collaborator already exists in the database based on firstName and lastName
     * @param objectToCheck the Collaborator to check
     * @return the id of the found Collaborator, or -1 if none exists
     * @throws SQLException if the database could not be reached
     */
    protected int checkAlreadyExists(Collaborator objectToCheck) throws SQLException {
        Connection connection = Database.getConnection();
        String query = "SELECT " + FIELD_ID + " FROM " + TABLE +
                " WHERE " + FIELD_FIRSTNAME + " = ? AND " + FIELD_LASTNAME + " = ?";
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            stmt = connection.prepareStatement(query);
            stmt.setString(1, objectToCheck.getFirstName());
            stmt.setString(2, objectToCheck.getLastName());

            rs = stmt.executeQuery();
            if (rs.next())
                return rs.getInt(FIELD_ID);
        } finally {
            closeStatementAndResulSet(stmt, rs);
        }
        return -1;
    }

    /**
     * Build a Collaborator object from the current row of a ResultSet
     * @param result the ResultSet positioned on the row to read
     * @return the Collaborator built from the row
     * @throws SQLException if the database could not be reached
     */
    protected Collaborator getResult(ResultSet result) throws SQLException {
        return new Collaborator(
                result.getInt(FIELD_ID),
                result.getString(FIELD_FIRSTNAME),
                result.getString(FIELD_LASTNAME)
        );
    }
}